# Use official Node.js image
FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy bot code
COPY ./monitor_bot/package.json ./package.json

# Install dependencies
RUN npm install


# Copy bot code
COPY ./monitor_bot/ ./


# Expose port and start bot
EXPOSE 3000
CMD ["npm", "start"]